package com.example.util

import com.example.data.model.AppLanguage

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        val isEs = lang == AppLanguage.SPANISH
        return when (key) {
            "app_title" -> if (isEs) "Control de Ventas" else "Retail POS"
            "daily_sales" -> if (isEs) "Ventas de Hoy" else "Today's Sales"
            "total_sold" -> if (isEs) "Total Vendido" else "Total Sold"
            "products" -> if (isEs) "Productos" else "Products"
            "history" -> if (isEs) "Historial" else "History"
            "reports" -> if (isEs) "Reportes" else "Reports"
            "settings" -> if (isEs) "Ajustes" else "Settings"
            "add_product" -> if (isEs) "Nuevo Producto" else "New Product"
            "edit_product" -> if (isEs) "Editar Producto" else "Edit Product"
            "delete_product" -> if (isEs) "Eliminar Producto" else "Delete Product"
            "product_name" -> if (isEs) "Nombre del Producto" else "Product Name"
            "price_usd" -> if (isEs) "Precio ($ USD)" else "Price ($ USD)"
            "price_bs" -> if (isEs) "Equivalente en Bolívares (Bs)" else "Equivalent in Bolívares (Bs)"
            "category" -> if (isEs) "Categoría" else "Category"
            "date" -> if (isEs) "Fecha" else "Date"
            "save" -> if (isEs) "Guardar" else "Save"
            "cancel" -> if (isEs) "Cancelar" else "Cancel"
            "delete" -> if (isEs) "Eliminar" else "Delete"
            "rate_usd" -> if (isEs) "Tasa $" else "Rate $"
            "update_rate" -> if (isEs) "Actualizar Tasa del Dólar" else "Update Dollar Exchange Rate"
            "enter_rate" -> if (isEs) "Tasa de cambio (Bs por $1 USD):" else "Exchange rate (Bs per $1 USD):"
            "sale_in_progress" -> if (isEs) "Venta en Proceso" else "Sale in Progress"
            "unit_price" -> if (isEs) "Precio unitario" else "Unit price"
            "quantity" -> if (isEs) "Cantidad" else "Quantity"
            "total_sale" -> if (isEs) "Total de la Venta" else "Sale Total"
            "ask_add_more" -> if (isEs) "¿Deseas agregar otro producto a esta venta?" else "Do you want to add another product to this sale?"
            "add_more_btn" -> if (isEs) "+ Agregar otro producto" else "+ Add another product"
            "checkout_btn" -> if (isEs) "Totalizar y Cobrar" else "Checkout & Totalize"
            "select_payment" -> if (isEs) "Selecciona el método de pago:" else "Select payment method:"
            "cash" -> if (isEs) "Efectivo" else "Cash"
            "pago_movil" -> if (isEs) "Pago Móvil" else "Mobile Payment"
            "punto_venta" -> if (isEs) "Punto de Venta" else "POS Card Terminal"
            "finalize_sale" -> if (isEs) "Confirmar Venta" else "Confirm Sale"
            "void_sale" -> if (isEs) "Anular Venta" else "Void Sale"
            "void_sale_confirm" -> if (isEs) "¿Estás seguro de anular esta venta?" else "Are you sure you want to void this sale?"
            "sale_completed" -> if (isEs) "¡Venta Registrada con Éxito!" else "Sale Recorded Successfully!"
            "new_sale" -> if (isEs) "Nueva Venta" else "New Sale"
            "back_to_home" -> if (isEs) "Volver al Inicio" else "Back to Home"
            "share_image" -> if (isEs) "Compartir Imagen" else "Share as Image"
            "search_hint" -> if (isEs) "Buscar por producto o recibo..." else "Search by product or receipt..."
            "filter_all" -> if (isEs) "Todos" else "All"
            "daily_report" -> if (isEs) "Reporte Diario" else "Daily Report"
            "weekly_report" -> if (isEs) "Reporte Semanal" else "Weekly Report"
            "monthly_report" -> if (isEs) "Reporte Mensual" else "Monthly Report"
            "weekly_average" -> if (isEs) "Promedio Semanal" else "Weekly Average"
            "breakdown_by_payment" -> if (isEs) "Desglose por Método de Pago" else "Breakdown by Payment Method"
            "grand_total" -> if (isEs) "Total General (Todos los métodos)" else "Grand Total (All methods)"
            "no_sales_yet" -> if (isEs) "No hay ventas registradas aún." else "No sales recorded yet."
            "no_products_yet" -> if (isEs) "No hay productos registrados. Presiona '+' para agregar." else "No products yet. Press '+' to add."
            "change_theme" -> if (isEs) "Cambiar Tema" else "Change Theme"
            "theme_green" -> if (isEs) "Gris & Verde Neón" else "Dark Gray & Neon Green"
            "theme_blue" -> if (isEs) "Gris & Azul Eléctrico" else "Dark Gray & Electric Blue"
            "dark_mode" -> if (isEs) "Modo Oscuro" else "Dark Mode"
            "light_mode" -> if (isEs) "Modo Claro" else "Light Mode"
            "language" -> if (isEs) "Idioma" else "Language"
            "company_logo" -> if (isEs) "Logotipo de la Empresa" else "Company Logo"
            "change_logo" -> if (isEs) "Cambiar Logo" else "Change Logo"
            "remove_logo" -> if (isEs) "Quitar Logo" else "Remove Logo"
            "receipt" -> if (isEs) "Recibo de Venta" else "Sale Receipt"
            "status" -> if (isEs) "Estado" else "Status"
            "voided" -> if (isEs) "ANULADA" else "VOIDED"
            "completed" -> if (isEs) "COMPLETADA" else "COMPLETED"
            "items_count" -> if (isEs) "artículos" else "items"
            else -> key
        }
    }
}
